
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - WebPageScanner

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

disabled_rules:
  - opening_brace
  - vertical_parameter_alignment
  - closure_end_indentation
  - missing_docs
  - implicitly_unwrapped_optional
  - no_extension_access_modifier

opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_cast
  - conditional_returns_on_newline
  - force_unwrapping
  - private_outlet
  - redundant_nil_coalesing
  - trailing_whitespace
  - closure_spacing
  - explicit_init
  - redundant_nil_coalescing
  - nimble_operator
  - overridden_super_call
  - file_header
  - number_separator
  - attributes
  - operator_usage_whitespace
  - prohibited_super_call
  - switch_case_on_newline
  - first_where
  - object_literal
  - explicit_type_interface
  - fatal_error_message
  - large_tuple
  - extension_access_modifier
  - explicit_top_level_acl
  - implicit_return
  - empty_enum_arguments
  - protocol_property_accessors_order
  - for_where
  - unused_optional_binding

force_cast: warning # implicitly

force_try:
  severity: warning

private_outlet:
  allow_private_set: true

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 65
    error: 70
  excluded:
    - API

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - log
    - _code
    - _domain

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  WebPageScanner
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}(\d{2})?\.
                    \/\/  Copyright © \d{4} Vitalii Budnik\. All rights reserved\.
                    \/\/

colon:
  apply_to_dictionaries: false
